; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Adok Install services"
#define MyAppVersion "1"
#define MyAppPublisher "Adok le Hub tactile"
#define MyAppURL "https://www.getadok.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7FB4B924-5D45-4FFC-A59B-1475E2D6667A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
PrivilegesRequired=admin
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}

; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=Adok Install services
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Files]
Source: "C:\Users\ageng\Downloads\exe_Congatec-20240502T073117Z-001\exe_Congatec\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonstartup}\Adok Action Centre"; Filename: "{app}\AdokActionCenterCng\AdokActionCenter.exe"
Name: "{commonstartup}\Adok Batt"; Filename: "{app}\AdokBatteryIconCng\AdokBatteryIconCng.exe"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{group}\Calib Usine"; Filename: "{app}\Calibration USINE Cng\CalibrationUsineCng.exe"; WorkingDir: "{app}\Calibration USINE Cng"; 
Name: "{group}\ROICalibration"; Filename: "{app}\ROICalibrationV3\ROICalibrationV3.exe"; WorkingDir: "{app}\ROICalibrationV3";

[Run]
Filename: "{app}\AdokWindowsShutdownCng\installutil.exe"; Parameters: "/LogToConsole=false ""{app}\AdokWindowsShutdownCng\AdokWindowsShutdownCng.exe"""; Flags: runhidden waituntilterminated; Description: "Install Adok ShutDown Service"
Filename: "{app}\AdokStartControlCng\installutil.exe"; Parameters: "/LogToConsole=false ""{app}\AdokStartControlCng\AdokStartControlCng.exe"""; Flags: runhidden waituntilterminated; Description: "Install Adok Start Control Service"
Filename: "{app}\DriversW10\CgbcSer\setup.exe"; WorkingDir: "{app}\DriversW10\CgbcSer"; Flags: runhidden skipifdoesntexist postinstall waituntilterminated; Description: "Run setup CgbcSer"
Filename: "{app}\DriversW10\Cgos-x64-Windows10\InstallCGOS.bat"; WorkingDir: "{app}\DriversW10\Cgos-x64-Windows10"; Flags: runhidden skipifdoesntexist postinstall waituntilterminated; Description: "Run InstallCgos"
Filename: "{app}\DriversW10\Intel_drivers_support\SetupChipset.exe"; WorkingDir: "{app}\DriversW10\Intel_drivers_support"; Flags: runhidden skipifdoesntexist postinstall waituntilterminated; Description: "Run Intel driver"