name: Build Installer

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Inno/version_1.iss
          options: /O+.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: <1.0.1>
          release_name: <Release 1.0.1>
          draft: false
          prerelease: false

      - name: Upload Installer to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Inno/Output/Adok Install Services.exe  # Update this path based on where your .exe is located
          asset_name: Adok Install Services.exe
          asset_content_type: application/octet-stream
